name: Build image test

on:
  push:
    branches:
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-and-deploy:

    runs-on: ubuntu-latest
    timeout-minutes: 600

    steps:
      - uses: actions/checkout@v2

      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: .cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-

      - name: Build Docker Image
        run: |
          docker build -t testimage:latest .

      - name: Copy cache
        working-directory: .cache
        run: |
          docker run -d --entrypoint /bin/sleep --name cache testimage:latest 300
          docker cp cache:/root/.cache/pip .
          docker kill cache
